### ISSUE TITLE
Size is changed when I convert docx to pdf

### ISSUE THREAD

**Issue by did0824** [elwerene/libreoffice-convert#101]
Hi I used this library very well, but  I got a problem when converting docx to pdf. 
Pdf size is smaller than docx.

docx:
<img width="1759" alt="Screenshot 2023-10-12 at 11 10 34" src="https://github.com/elwerene/libreoffice-convert/assets/37896341/57a75892-a54d-4d78-9bbb-f6b9126149f8">

pdf:
<img width="902" alt="Screenshot 2023-10-12 at 11 11 05" src="https://github.com/elwerene/libreoffice-convert/assets/37896341/900e23de-4bc2-406a-87d9-e8eec9ff0326">

**Comment by elwerene** [comment]
Please check if Libreoffice has the same issue and open a ticket on their issue tracker. If it's only an issue here you can reopen the ticket here
