### ISSUE TITLE
Parallel conversion and express conversion API

### ISSUE THREAD

**Issue by woodholly** [elwerene/libreoffice-convert#102]
Several years ago I used libreoffice to convert documents and I remember it had problems with parallel execution.
Was it fixed ? Can libreoffice-convert act in parallel and is there some express api app for that ?
If not, is there any express api app with workaround (queue with pause to prevent parallel execution) for that ?

**Comment by elwerene** [comment]
I don't know but I remember someone added a cli option to our libreoffice call which fixed that. Please try :)
