### ISSUE TITLE
Azure App Service support

### ISSUE THREAD

**Issue by alexeybreusov5** [elwerene/libreoffice-convert#11]
I use this package for backend development to convert docx to pdf. I works fine on my local since libre office has been installed. But once I deploy it to azure app service, it doesn't work. Is there any way to fix this issue?

**Comment by alexeybreusov5** [comment]
Can I solve this issue by uploading libre office package to certain path in app service?

**Comment by elwerene** [comment]
I never used Azure App Service. If it is possible to install Libreoffice, then it might work.

I quickly researched and found that it might be possible to use custom docker images on azure app service. So you need a docker Image with nodejs and Libreoffice. Maybe combining a nodejs and a libreoffice docker image could work out for you!

**Comment by alexeybreusov5** [comment]
@elwerene , thanks for your quick response. I will try out your recommendation and let you know.

**Comment by alexeybreusov5** [comment]
@elwerene , I did exactly what you said and solved the issue using docker image in azure.
