### ISSUE TITLE
The selection style is moving out

### ISSUE THREAD

**Issue by vokmar** [elwerene/libreoffice-convert#111]
How to beat this
![image](https://github.com/elwerene/libreoffice-convert/assets/65220655/bacb4899-ddd7-44ba-ac50-31f678a91933)

`
const converterDOCX = async (path)=>{
    const regex = /\.docx/i;
    const pathPDF = path.replace(regex, '.pdf');
    const docxBuf = await fs.readFile(path);
    console.log(process.env)
    console.log(process.env.PROGRAMFILES)
   await convert(docxBuf,'pdf',undefined,(err,done)=>{
        console.log(err)
        console.log(done)
       if(done)
         fs.writeFile(pathPDF, done)
    })
}
`

**Comment by elwerene** [comment]
As always the question if it is working in libreoffice. If it works in Libreoffice and not in this lib, it might be a bug of this lib and you can reopen the issue. If it does not work in Libreoffice, please open a bug report in their issue tracker. Thank you

**Comment by vokmar** [comment]
![image](https://github.com/elwerene/libreoffice-convert/assets/65220655/a7f3f6a9-8627-4178-8142-473b8bc09634)

**Comment by vokmar** [comment]
I'll try printing later
