### ISSUE TITLE
fixing conversion issues

### ISSUE THREAD

**Issue by vokmar** [elwerene/libreoffice-convert#112]
This can be fixed
![1](https://github.com/elwerene/libreoffice-convert/assets/65220655/0cb15ec8-0fc8-4226-b2fc-b0afaaf54337)
![2](https://github.com/elwerene/libreoffice-convert/assets/65220655/862a58da-e106-472f-855d-a1453636bebf)

**Comment by elwerene** [comment]
I don't get it. It looks like libreoffice convert produces the same results as libreoffice writer?

**Comment by vokmar** [comment]
> Не понимаю. Похоже, что libreoffice convert дает те же результаты, что и libreoffice writer?

exactly.
![image](https://github.com/elwerene/libreoffice-convert/assets/65220655/bbc120b8-150a-4e63-8c47-ab4ae8d491df)

**Comment by vokmar** [comment]
> Не понимаю. Похоже, что libreoffice convert дает те же результаты, что и libreoffice writer?
For Excel, too.
Embedded tables are not displayed as in MS Office

![image](https://github.com/elwerene/libreoffice-convert/assets/65220655/a63ca824-ef3d-40d0-9f4e-801ff1c8a729)

**Comment by elwerene** [comment]
I still don't get what this library is doing wrong. If you want the same results as microsoft excel you would need to try to do it with microsoft excel, maybe there's an api for that
