### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by skashequr** [elwerene/libreoffice-convert#115]
let pdfBuf = await libre.convertAsync(docxBuf, ext, undefined);
when i write this code then crash my surver and throw Error converting file: Error: Could not find soffice binary 
and Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\USER\AppData\Local\Temp\libreofficeConvert_-9776-EAsVmro1lFpe'

**Comment by elwerene** [comment]
duplicate of https://github.com/elwerene/libreoffice-convert/issues/114

**Comment by elwerene** [comment]
@skashequr please stop opening new issues

**Comment by skashequr** [comment]
How can i handle this issue? Can you guide me?

**Comment by elwerene** [comment]
`Please install libreoffice in /Applications (Mac), with your favorite package manager (Linux), or with the msi (Windows).`

https://github.com/elwerene/libreoffice-convert/blob/master/Readme.md

**Comment by skashequr** [comment]
I already install LibreOffice_24.2.0_Win_x86-64 this application .Now my
convert is working.What is the solution when I deploy my backend code is
not working?

**Comment by elwerene** [comment]
That depends on your server setup. I'm sorry I can not give an easy answer to this. You might need to ask your it
