### ISSUE TITLE
Hard to reproduce the readme

### ISSUE THREAD

**Issue by pjerryhu** [elwerene/libreoffice-convert#118]
Hey, I'm having trouble reproducing the readme example. 

Specifically, I use typescript, and cannot seem to find where the util is from by line

```
libre.convertAsync = require('util').promisify(libre.convert);
```

**Comment by elwerene** [comment]
@pjerryhu https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original
