### ISSUE TITLE
The conversion of footer text from DOCX to PDF is not done properly

### ISSUE THREAD

**Issue by roughsky** [elwerene/libreoffice-convert#124]
I tried to convert a docx file to pdf and noticed that the footer text is not able to convert properly. For eg in the below attached screenshots, the value for text "Document type" is not converted properly and is getting hardcoded to "source" while another footer in next line named "Date" is fine. Rest of the file is good. I'm using v1.5.1 by the way.

Screenshots:

> Docx
<img width="1050" alt="Screenshot 2024-07-16 at 7 22 01 PM" src="https://github.com/user-attachments/assets/3babb6a7-11a5-4f78-bfc9-4a51a7914fc4">

> Pdf
<img width="1061" alt="Screenshot 2024-07-16 at 7 21 36 PM" src="https://github.com/user-attachments/assets/9eb524ff-7a4f-41e6-909b-38694fdda5df">

PFB the file which was used for conversion:
[Footer Issue.docx](https://github.com/user-attachments/files/16251569/Footer.Issue.docx)

**Comment by roughsky** [comment]
When exporting this DOCX file to PDF in LibreOffice, it actually overrides the value under "Document Name" with the file name.

PFB ss:
<img width="1096" alt="Screenshot 2024-07-17 at 11 15 36 AM" src="https://github.com/user-attachments/assets/5a89a04f-8622-4845-8e34-452357eecab4">

**Comment by roughsky** [comment]
Hey Rene,
Can you share any update pls?

**Comment by elwerene** [comment]
Not really. If it does not work in libreoffice, it can not work in this library..

**Comment by elwerene** [comment]
Then I missunderdtood your comment. Did you export to pdf in libreoffice or print to pdf? That's a difference..

**Comment by roughsky** [comment]
Export to pdf

**Comment by elwerene** [comment]
So the document uses the name of the file in this.

@roughsky You could make a pr to make this configurable. Changes are needed wherever "source" is mentioned. You could add this to the options and keep the default "source".

If you make the pr, I'm happy to review and release it.

**Comment by elwerene** [comment]
Fix is released in version 1.6.0. Thanks @roughsky
