### ISSUE TITLE
process.env.LIBREOFFICE_PATH shows as undefined

### ISSUE THREAD

**Issue by nkarchana** [elwerene/libreoffice-convert#128]
Hi,

We are trying to do fileconversion from certain extensions like docx or pptx formats to pdf format using the libre-office library. Below is the code used for conversion.
const options = {
            sofficeBinaryPaths: [process.env.LIBREOFFICE_PATH],
        };
        const pdfBuf = await libre.convertWithOptions(
            docxBuf,
            ext,
            undefined,
            options,
            undefined
        );
In AWS Lambda we are adding the libre office layer as below. 
name - libreoffice-gzip
 
arn = arn:aws:lambda:us-east-1:764866452798:layer:libreoffice-gzip:1
 
![image](https://github.com/user-attachments/assets/c31ee355-c588-41ec-8286-55881ae07e6c)

With these changes I am getting an error saying process.env.LIBREOFFICE_PATH is undefined. What should be configured as the process.env.LIBREOFFICE_PATH path while deploying the code?

**Comment by elwerene** [comment]
Why are you using `process.env.LIBREOFFICE_PATH` in the first place? Did you copy that code from somewhere? Install libreoffice and set the path and it will work!

**Comment by nkarchana** [comment]
@elwerene  What should I add as the process.env.LIBREOFFICE_PATH when its deployed on AWS server?

**Comment by elwerene** [comment]
@nkarchana The path to your libreoffice installation path on the aws server. I have no idea how aws servers look like and how you can install software there..
