### ISSUE TITLE
soffice.bin is taking up almost 100% CPU

### ISSUE THREAD

**Issue by naveenwc** [elwerene/libreoffice-convert#129]
Please find the results of top on our AWS machine and the code snippet we are using, is there any reason for this to happen?

```
import libre from 'libreoffice-convert';

const convertAsync = promisify(libre.convertWithOptions);
await convertAsync(buffer, ext, und, {
      sofficeBinaryPaths: [process.env.libreOfficePath],
    });
```

<img width="1199" alt="Screenshot 2024-10-07 at 7 55 19 PM" src="https://github.com/user-attachments/assets/2d5490a2-f889-4b27-a203-fffa832068bc">

<img width="784" alt="Screenshot 2024-07-07 at 8 39 31 PM" src="https://github.com/user-attachments/assets/9b4e410e-4018-4e4d-92af-f21a19e046e2">

**Comment by elwerene** [comment]
I guess you are trying to convert a big file or lots of files? soffice is doing the main job here and it's probably not very well optimized.
