### ISSUE TITLE
Support browsers

### ISSUE THREAD

**Issue by monarchwadia** [elwerene/libreoffice-convert#132]
Is this even possible? :)

**Comment by elwerene** [comment]
No, sorry.

**Comment by monarchwadia** [comment]
Thanks @elwerene , I had a question for you if it's okay. 

I'm thinking of wrapping up LibreOffice using Emscripten for my own project at work. I understand `libreoffice-convert` is specifically built for Node... but is the reason not to support browsers something to do with `libreoffice-convert`'s goals? Or is it more to do with the underlying LibreOffice source code?

I.e. is there something inside LibreOffice that prevents browser support?

**Comment by elwerene** [comment]
libreoffice-convert just calls the libreoffice convert binary in the system. As you can not call binaries from the browser in the users system for obvious reasons, this is not possible. Maybe you can compile libreoffice to the browser, but this would be a horrific idea in my opinion and would have nothing to do with this library!

**Comment by monarchwadia** [comment]
Whoops! I thought y'all were doing the WASM path. OK this makes more sense!
