### ISSUE TITLE
Enhancement: Does it support stream?

### ISSUE THREAD

**Issue by SushKenyNeosoft** [elwerene/libreoffice-convert#17]
Does this library support streams API? It would be great if it would!

**Comment by elwerene** [comment]
sadly it doesn't! I will review your PR if you want to work on it. 

Am 18. Februar 2020 11:40:35 MEZ schrieb SushKenyNeosoft <notifications@github.com>:
>Does this library support streams API? It would be great if it would!

**Comment by SushKenyNeosoft** [comment]
> sadly it doesn't! I will review your PR if you want to work on it. Am 18. Februar 2020 11:40:35 MEZ schrieb SushKenyNeosoft <notifications@github.com>:
> […](#)
> Does this library support streams API? It would be great if it would!

Sure, I would love to give a try :)
