### ISSUE TITLE
Does not work in parallel

### ISSUE THREAD

**Issue by FrozenAlex** [elwerene/libreoffice-convert#21]
When I try to make 2 or more simultaneous conversions it always fails. 
It would be nice to be able to use promises with the library

**Comment by elwerene** [comment]
I'm not actively working on this package. If you provide a merge request I will take the time to review it and push a new version.

**Comment by bgorhoball** [comment]
Is it possible to have an option to allow running multiple instances of libreoffice?
I found the below article achieving this by adding 
"-env:UserInstallation=file:/${random_temp_path}"

https://ask.libreoffice.org/en/question/42975/how-can-i-run-multiple-instances-of-sofficebin-at-a-time/
