### ISSUE TITLE
Specify custom binary path

### ISSUE THREAD

**Issue by mimedo** [elwerene/libreoffice-convert#22]
My applications runs on Heroku (where you can deploy your node application) and in this application I use your library.

Because the default binary path is not `/usr/bin/soffice` or `/usr/bin/libreoffice` it fails to convert my libreoffice document.

Is it possible to specify a custom binary path?

**Comment by elwerene** [comment]
Not yet. Maybe you can add that feature and provide a pull request? I will review and accept it if it works :)

**Comment by elwerene** [comment]
@mimedo you could use the new options object to introduce this feature
