### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by squalsoft** [elwerene/libreoffice-convert#3]
Hi! Thank you for your great small library! I use it on latest node.js and on run i receive warning:
(node:30076) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead

Can you fix it?

**Comment by elwerene** [comment]
I will not invest much work in this library anymore, as I will replace it in my projects with a more complete version which supports streaming as well. (I didn't yet search for the other version to guide you there). 

If you fix it yourself, I will accept the merge request and publish it to npm!
