### ISSUE TITLE
linux yum installs libreoffice under the /opt/ folder

### ISSUE THREAD

**Issue by Danijj89** [elwerene/libreoffice-convert#31]
Hi,

I'm trying to use libreoffice-convert on an aws ec2 instance.

In order to make the module work I had to install libreoffice on the linux machine.
However, the package manager (yum) installs it on /opt/libreoffice6.4/program/soffice, 
while the convert function only looks under /usr/bin folder and cannot find it.

Any help would be appreciated.

Thanks

**Comment by elwerene** [comment]
you have two choices:
* write a pr with the added path
* link your soffice binary: `ln - s /opt/libreoffice6.4/program/soffice /usr/bin/soffice`

Am 13. August 2020 01:49:04 MESZ schrieb Danijj89 <notifications@github.com>:
>Hi,
>
>I'm trying to use libreoffice-convert on an aws ec2 instance.
>
>In order to make the module work I had to install libreoffice on the linux machine.
>However, the package manager (yum) installs it on /opt/libreoffice6.4/program/soffice, 
>while the convert function only looks under /usr/bin folder and cannot find it.
>
>Any help would be appreciated.
>
>Thanks
>
>
>

**Comment by Danijj89** [comment]
Hi,

Thanks for your help!
I followed your suggestion and created a symlink, and it solved my issue.
I will keep an eye on #25
