### ISSUE TITLE
Doesn't work in windows

### ISSUE THREAD

**Issue by kennylbj** [elwerene/libreoffice-convert#32]
It works well in OSX but when I deploy it to windows(both in win10 and win7) it failed, and the error is something like:

> The program can't start because the config file [C:\Program Files\LibreOffice\program\bootstrap.ini] has corrupted.

I do check the bootstrap.ini file and find that content is well defined.

However, I can open soffice.exe and lanch LibreOffice by clicking the file Icon.

LibreOffice version: V7.0 (lastest)

**Comment by elwerene** [comment]
what happens if you run soffice.exe with th the same convert arguments as it is called with this lib?

**Comment by kennylbj** [comment]
I manually remove `-env:UserInstallation=file://${installDir.name}` in index.js and everything work well again.

```js
// change
let command = `${results.soffice} -env:UserInstallation=file://${installDir.name} --headless --convert-to ${format}`;

// to 
let command = `${results.soffice}  --headless --convert-to ${format}`;
```

I don't know what happened under the hood but it actually works. what's the meaning of -env argument?

**Comment by elwerene** [comment]
@kennylbj https://github.com/elwerene/libreoffice-convert/pull/27

**Comment by ilkohoffmann** [comment]
`installDir.name` is not a valid POSIX format which is expected by the binary. Converting the dir to POSIX on line 46 fixes that issue:

```
// convert installDir to POSIX format
// to prevent problems on Windows OS
const posixInstallDir = installDir.name.split(path.sep).join(path.posix.sep);
let command = `-env:UserInstallation=file:///${posixInstallDir} --headless --convert-to ${format}`;
```

**Comment by ilkohoffmann** [comment]
From Pull-request https://github.com/elwerene/libreoffice-convert/pull/47#issuecomment-724867127

> 
> 
> @ilkohoffmann Doesn't this break on windows?
> In the [documentation](https://nodejs.org/api/path.html#path_path_sep) it says, the `path.sep` is `\` in windows which is correct as far as I know. You replace it with `path.posix.sep` which should always be `/` - I can't test it on Windows as I don't have access to a installation.
> Or did I miss a change in Windows path behavior and it now accepts `/`?

Not changing the `\` to `/` causes a break on windows. Without the change the resulting command looks like this:
```javascript
// line 50
`soffice.exe -env:UserInstallation=file://C:\Users\<USER>\AppData\Local\Temp\soffice-5568-<XXXX>`
```
causing the error @kennylbj mentioned above. I couldn´t find any good documentation to the headless soffice converter and the available parameterization. I believe that the `-env` parameter expects a posix compliant format rather than a windows path expression because its handled internally. I have tested it on windows and it seems to work now. The path is created on the corresponding tmp location and removed after succesful execution. I have closed the pull request anyway, because their is another change to make on windows and I am not sure if that will still work on unix-based systems. The expression with two trailing slashes after file
````javascript
// line 50
let command = `-env:UserInstallation=file://${posixInstallDir} --headless --convert-to ${format}`;`
````
has to be changed to three trailing slashes
````javascript
// line 50
let command = `-env:UserInstallation=file:///${posixInstallDir} --headless --convert-to ${format}`;`
````

**Comment by ilkohoffmann** [comment]
I have stumbled across the "file URI scheme" which explains why this is working: https://en.wikipedia.org/wiki/File_URI_scheme

**Comment by JCLimpide** [comment]
As of Feb 21, running on the same error, a variant of @kennylbj solution worked for me:

index.js L46
`            // let command = `-env:UserInstallation=file://${installDir.name} --headless --convert-to ${format}`;
            let command = `--headless --convert-to ${format}`;
`

**Comment by elwerene** [comment]
Please try https://github.com/elwerene/libreoffice-convert/pull/51

**Comment by avimar** [comment]
This is still an issue on windows 10 with version 1.3.5

**Comment by mihir254** [comment]
Came across the same issue on windows. Installed LibreOffice and checked the file path mentioned in the node module to make it work.
Code looks like:
`const libre = require('libreoffice-convert');`
`libre.convertAsync = require('util').promisify(libre.convert);`
`const pdfBuf = await libre.convertAsync(doc.getZip().generate({`
`    type: "nodebuffer",`
`    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",`
`}), 'pdf', undefined);`

And then I proceeded with using the buffer according to my use case. Thank you for sharing the resources in the above comments, it helped a lot!
Cheers!
