### ISSUE TITLE
Receiving error: no such file or directory, open "/var/folders/...../source..html"

### ISSUE THREAD

**Issue by polp6880** [elwerene/libreoffice-convert#33]
Hi,

I was able to successfully use the library to convert local files stored on the same server by following the example code. I now, however, would like to convert a remote file.

My idea was to read the file's content first (via request) and then pass the body received to libreoffice-convert.

Below is the code I'm using:

```
request(fileUrl, {encoding: 'binary'}, function(error, response, body) {
    const ext = '.html';

    libre.convert(body, ext, undefined, (err, done) => {
      if (err) {
        console.log(`Error converting file: ${err}`);
        res.sendStatus(500);
      } else {
        console.log(done);
      }
    });

  });
```

I can see that when I run this, libreoffice starts the conversion but eventually, I'm getting this error:
`Error: ENOENT: no such file or directory, open '/var/folders/j9/z_z85kh5501dbslrg53mpjsw0000gn/T/libreofficeConvert_-6529-x08o2o3peLMh/source..html`

Is there something I'm missing?

Thanks!

**Comment by conor-odro** [comment]
We are having a similar issue converting from .docx to .pdf

`Error converting file: Error: ENOENT: no such file or directory, open '/tmp/libreofficeConvert_-31919-42V7nBFvIGdA/source..pdf'`

I can convert files locally on my Macbook Pro easily, but on an AWS Production Linux server we seem to get the above issue. I found some discussion [here](https://ask.libreoffice.org/en/question/198713/executed-from-linux-command-line-convert-to-is-unexpectedly-asynchronous/) and [here](https://bugs.documentfoundation.org/show_bug.cgi?id=117731) suggesting there is a difference with how LibreOffice runs commands on Linux compared to Mac/Windows.

@polp6880 Did you happen to find a solution?

**Comment by polp6880** [comment]
@conor-odro from our end we decided to go in a bit of a different route. The production environment is set on K8 and a docker container so instead of passing the remote file's URL directly, we're grabbing a copy of the file's content, save it in memory and then pass it to libreoffice as if it was a local file. This worked fine so far.
