### ISSUE TITLE
Error converting file: Error: Could not find soffice binary  On Firebase Cloud functions

### ISSUE THREAD

**Issue by Hanzala717** [elwerene/libreoffice-convert#37]
I'm trying to convert file to pdf in **firebase cloud function** but it causing crash 

`Error converting file: Error: Could not find soffice binary `

please let me know if it is supported with cloud function or not and whats best approach for it.

**Comment by elwerene** [comment]
@Hanzala717 I don't know about firebase cloud function. Did you install libreoffice on it as stated in the Readme?

**Comment by Hanzala717** [comment]
yes I did same and it shows **Error converting file: Error: Could not find soffice binary**

**Comment by elwerene** [comment]
@Hanzala717  Where is your soffice binary located on the server?

**Comment by elwerene** [comment]
You can find it with the command `which soffice`.

**Comment by Hanzala717** [comment]
I'm using firebase functions and I just installed this by using npm and after that deployed to firebase server all libs modules are bundled in same folder

**Comment by Hanzala717** [comment]
how to install it on firebase server?

**Comment by elwerene** [comment]
I don't know how to install libreoffice on firebase server
