### ISSUE TITLE
Error converting file

### ISSUE THREAD

**Issue by hkhoan90** [elwerene/libreoffice-convert#42]
Error converting file: Error: spawn "C:\Program Files\LibreOffice\program\soffice.exe" ENOENT
I installed LibreOffice in the correct location already.

**Comment by AaryanAdil** [comment]
Same error occurs on my side.

**Comment by ilkohoffmann** [comment]
I had the same problems on Windows OS. Removing the quotes of the soffice binary location fixes that problem:

`results.soffice = results.soffice.replace(/"/g, '');`

**Comment by elwerene** [comment]
@ilkohoffmann can you please provide a pull request?
