### ISSUE TITLE
Pdf converted from word only display number on result.

### ISSUE THREAD

**Issue by vulgoplus** [elwerene/libreoffice-convert#43]
Sorry for my bad english.
I has use libreoffice convert in linux system and this is my result:
[customer_po_0005.BBV (1).pdf](https://github.com/elwerene/libreoffice-convert/files/5463035/customer_po_0005.BBV.1.pdf)

Seem all character are wrong fonts

How can i fix it.

**Comment by vulgoplus** [comment]
I solved it. I missing fonts in alpine linux. 
But still wrong font in some section.

**Comment by HwangTaehyun** [comment]
I solved the same issue by adding the font used by the word file to transform
