### ISSUE TITLE
Specify other directory for libreoffice instalation

### ISSUE THREAD

**Issue by Pibomeister** [elwerene/libreoffice-convert#49]
Is there any way to specify a different path for the libreoffice instalation in Linux other than the default:
`['/usr/bin/libreoffice', '/usr/bin/soffice']`
paths?

I am trying to run this package within heroku but my libreoffice installation is under:

`$HOME/vendor/libreoffice`

I can't use `ln -s` or `mount --bind` commands to link this path to the default paths since there is no super user access on heroku. 

Any help is appreciated!

**Comment by elwerene** [comment]
No yet. You could extend the options object with a custom installation path variable and use that in the `soffice` async task. If you are making a merge request, I will happily review and merge it :)

**Comment by shimcup** [comment]
Any update on this?

**Comment by elwerene** [comment]
I didn't yet receive a pull request for this, so no. Feel free to make a pull request, I only passively maintain this package.
