### ISSUE TITLE
Convert filter "Rich Text Format" - "MS Word 2007 XML"

### ISSUE THREAD

**Issue by lener18** [elwerene/libreoffice-convert#52]
does not work with this
soffice --headless --convert-to rtf: "Rich Text Format" --outdir /var/www/docstore.service/ /var/www/docstore.service/122.html
when it does the split it generates an error

valid filters: https://help.libreoffice.org/latest/he/text/shared/guide/convertfilters.html

**Comment by elwerene** [comment]
if soffice does throw an error, this library can't do much about it :/
