### ISSUE TITLE
Error: Could not find soffice binary

### ISSUE THREAD

**Issue by aruproy** [elwerene/libreoffice-convert#56]
Hi there -
I have installed [LibreOffice on Amazon Linux](https://gist.github.com/umair-khokhar/11516a692a21d3de05751f50056bf4dd) using RPMs and updated the PATH variable.

Binary version: [LibreOffice_7.1.4_Linux_x86-64_rpm](http://download.documentfoundation.org/libreoffice/stable/7.1.4/rpm/x86_64/LibreOffice_7.1.4_Linux_x86-64_rpm.tar.gz) 
Install location: /opt/libreoffice7.1/program/

I can see the soffice.bin file and can access it from my NodeJs deployment directory (without specifying the absolute path). However, at runtime the `libre.convert` call is throwing error -
**Error: Could not find soffice binary**

I am stuck here. I would greatly appreciate any help in resolving this issue.

**Comment by elwerene** [comment]
Ahoi! You just reported an issue which is already open: #49 
You can crate a pull request and I can happily review and merge it!

**Comment by aruproy** [comment]
@elwerene Thank you for pointing me to the right direction.

Leaving notes for others -

The 'libreoffice-convert' library expects for the soffice binary under `/usr/bin/soffice`
`which soffice` command allowed me to reconfirm the installation path.
Then mapped the installation path `ln -s /opt/libreoffice7.1/program/soffice /usr/bin/soffice`

That's all!
