### ISSUE TITLE
Output PDF font 

### ISSUE THREAD

**Issue by Jud-Ken-Do** [elwerene/libreoffice-convert#57]
Hi,
Thanks for this awesome package.

How can I keep the font used in the excel file.
The input xslx font is Calibri, but the output PDF is in Liberation.
I've changed the default font on LibreOffice to Carlito, but the headless doesn't take that into account.
Do you have any suggestion? 

Cheers,

**Comment by elwerene** [comment]
Hi @Jud-Ken-Do, I don't have any idea. Sorry.
Maybe ask at libreoffice project?

**Comment by Jud-Ken-Do** [comment]
@svandegar yes! 
For my case Calibri font wasn't installed on my OS. 
I just added it.

**Comment by svandegar** [comment]
Thank you so much for your answer!
