### ISSUE TITLE
@types support?

### ISSUE THREAD

**Issue by u007** [elwerene/libreoffice-convert#58]
hi,

can we have @types support for typescript?
currently im using this:

```
declare module 'libreoffice-convert' {
  export const convertWithOptions = (document: string, format: string,
  filter: string, options = {tmpOptions? : {}, asyncOptions? : {}}, 
  callback: (err: Error | undefined, any) => {
  
  }) => {}

  export const convert = (document: string, format: string,
  filter: string | undefined, callback: (err: Error | undefined, any) => {
  
  }) => {}
}

```

**Comment by elwerene** [comment]
Sure, please provide a pull request. I will review it and create a new version :) 

Am 3. August 2021 18:34:26 MESZ schrieb James ***@***.***>:
>hi,
>
>can we have @types support for typescript?
>currently im using this:
>
>```
>declare module 'libreoffice-convert' {
>  export const convertWithOptions = (document: string, format: string,
>  filter: string, options = {tmpOptions? : {}, asyncOptions? : {}}, 
>  callback: (err: Error | undefined, any) => {
>  
>  }) => {}
>
>  export const convert = (document: string, format: string,
>  filter: string | undefined, callback: (err: Error | undefined, any) => {
>  
>  }) => {}
>}
>
>```
>

**Comment by mingkyme** [comment]
I tried this code and worked.
```ts
declare module 'libreoffice-convert' {
    export const convert = (document: Buffer, format: string,
        filter: string | undefined, callback: (err: Error | undefined, any) => void) => { }
}
```

**Comment by elwerene** [comment]
If have no idea about typescript myself. I mostly switched to rust :shrug: 
So lets release this :)
