### ISSUE TITLE
Not working on heroku server with libreoffice buildpack 

### ISSUE THREAD

**Issue by williamlwallace** [elwerene/libreoffice-convert#60]
Hi I am using this package on my heroku server and have installed the [libreoffice buildpack](https://elements.heroku.com/buildpacks/bluetealondon/heroku-buildpack-libreoffice-for-heroku-18) for Heroku stack-18 however whenever I try to run this package to convert word docx to pdf on the server I get an error message saying soffice binary is not found.

If I run `heroku run soffice --version` is says that soffice is installed.

I'm wondering if anyone has successfully used this on a Heroku server

**Comment by elwerene** [comment]
I never used heroku. Feel free to provide a fix as pr!

**Comment by chenop** [comment]
Have you solved this issue?

**Comment by Axiean** [comment]
no

**Comment by elwerene** [comment]
duplicate of #85
