### ISSUE TITLE
just a q ? 

### ISSUE THREAD

**Issue by HassanDev13** [elwerene/libreoffice-convert#69]
can i implement this in my api on shared host ?

**Comment by elwerene** [comment]
What shared host are you talking about?

**Comment by HassanDev13** [comment]
It works fine on my local machine but when i deploy it to my online server
"shared host" I don't know how I can install libreoffice on cpanel or did I
need a VPS ?

**Comment by elwerene** [comment]
I don't know cpanel, but I guess you would need an own server/vm/docker to install libreoffice. If that's not possible for you, I would recommend to you another package.
