### ISSUE TITLE
embed images as base64 when outputting to html

### ISSUE THREAD

**Issue by danielzzz** [elwerene/libreoffice-convert#70]
hi, is it possible with this library to embed images as base64 when converting to html?

thanks, cheers, dan

**Comment by elwerene** [comment]
I don't know :)
It just uses libreoffice, so probably better ask this image on their git!

**Comment by danielzzz** [comment]
hmm it seems it's possible with libre office, but how do I pass options there?

**Comment by danielzzz** [comment]
nvm, checked the source, thx

**Comment by adithyakng** [comment]
@danielzzz , can you let me know the option that I should pass ?
