### ISSUE TITLE
Error converting file: Error: Command failed

### ISSUE THREAD

**Issue by haiduong2905** [elwerene/libreoffice-convert#72]
i get this Error.
`Error converting file: Error: Command failed: "C:\Program Files\LibreOffice\program\soffice.exe" -env:UserInstallation=file://C:\Users\DEV_CR~1\AppData\Local\Temp\soffice-6052-5bec0zaQKRBk --headless --convert-to .pdf --outdir C:\Users\DEV_CR~1\AppData\Local\Temp\libreofficeConvert_-6052-iBxGkJXLM0NO C:\Users\DEV_CR~1\AppData\Local\Temp\libreofficeConvert_-6052-iBxGkJXLM0NO\source`

**Comment by elwerene** [comment]
It seems you don't have libreoffice installed. 

Am 8. Januar 2022 10:36:47 MEZ schrieb haiduong2905 ***@***.***>:

**Comment by haiduong2905** [comment]
i installed and received notify `The application cannot be started. 
The configuration file "C:\Program Files\LibreOffice\program\bootstrap.ini" is corrupt.`

**Comment by elwerene** [comment]
Did you try to start libreoffice manually? It seems your Installation is corrupted

**Comment by ivysrono** [comment]
Same error.
I have try to start libreoffice manually, and it's OK.

Win10 x64
LibreOffice 7.2.5 x64
libreoffice-convert 1.3.5
NodeJs 16.13.1

**Comment by ccoenen** [comment]
I have the same problem as described in here. LibreOffice is installed, and `bootstrap.ini` can't be found.
