### ISSUE TITLE
Conversion is very slowly.

### ISSUE THREAD

**Issue by KamyarLajani** [elwerene/libreoffice-convert#76]
I just converted a 5MB of a .doc file and took 4.19 minutes to be completed!
And I converted another file with size of 99MB manually from LibreOffice program and took me similar to the previous one around 4 minutes. The same 99MB tested throw this module, it took me very long time not finished and I skipped it.
Thank you for your help.

**Comment by elwerene** [comment]
@KamyarLajani 

How long does the 5mb file take in libreoffice?

if it is still slow manually, you might want to report it at https://bugs.documentfoundation.org/

if is is a lot faster, try to convert it with the command line of libreoffice. If this is significantly faster than this lib, than reopen this issue!
