### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/tmp/libreofficeConvert_-32447-PWkldkvtqA0b/source..docx'

### ISSUE THREAD

**Issue by roverboy773** [elwerene/libreoffice-convert#81]
Error occurs when convert function is called

const path = require("path");
    const fs = require("fs").promises;

    const libre = require("libreoffice-convert");
    libre.convertAsync = require("util").promisify(libre.convert);

    (async function fn() {
      try {
        const ext = req.body.convertTo;

        const temp1 = req.body.data.resp.fileName.lastIndexOf(".");

        const inputPath = path.join(__dirname, "../", req.body.data.resp.path);
        const outputPath = path.join(
          __dirname,
          "../",
          `uploads/${req.body.data.resp.fileName.substring(0, temp1)}${ext}`
        );

        // Read file
        const docxBuf = await fs.readFile(inputPath);

        // Convert it to pdf format with undefined filter (see Libreoffice docs about filter)
        libre.convert(docxBuf, ext, undefined, (err, done) => {
          if (err) {
            console.log(docxBuf);
            console.log(`Error converting file: ${err}`);
            res.sendStatus(500);
          } else {
            console.log(done);
          }
        });
      } catch (err) { 
        console.log(err);
      }
    })();

output Error:Error converting file: Error: ENOENT: no such file or directory, open '/tmp/libreofficeConvert_-3947-L12WFnW9nmeG/source..docx'

**Comment by roverboy773** [comment]
req.body.data:={
    file: 'http://localhost:5000/files/a952e17d-aaed-4063-a771-bc726618df7f',
    resp: {
      expire_at: '2022-03-31T09:20:35.275Z',
      _id: '6245740e1b32170e250e910f',
      fileName: '1648718862144-0.9536543514182461.pdf',
      path: 'uploads/1648718862144-0.9536543514182461.pdf',
      size: 233836,
      uuid: 'a952e17d-aaed-4063-a771-bc726618df7f',
      file_owner: '61de5f132999590a308ecfdb',
      createdAt: '2022-03-31T09:27:42.154Z',
      updatedAt: '2022-03-31T09:27:42.154Z',
      __v: 0
    }
  }

**Comment by elwerene** [comment]
did you try running your code on a local file? This issue needs a lot more context!

**Comment by k163791** [comment]
> 

I ran into the same issue, i was using a local file, but the thing is i was trying to convert from pdf to docx, when i converted from docx to pdf everything ran smoothly, but i couldn't figure out why it was not working the other way around.

Does the library support conversions from pdf to other formats ?

**Comment by roverboy773** [comment]
> did you try running your code on a local file? This issue needs a lot more context!

yes, I used a local file, the server is running locally

**Comment by roverboy773** [comment]
> did you try running your code on a local file? This issue needs a lot more context!

yes, I used a local file, server was

**Comment by roverboy773** [comment]
> > 
> 
> I ran into the same issue, i was using a local file, but the thing is i was trying to convert from pdf to docx, when i converted from docx to pdf everything ran smoothly, but i couldn't figure out why it was not working the other way around.
> 
> Does the library support conversions from pdf to other formats ?

I haven't tried the other way out...I think the purpose of the library is to interconvert right?....rather than convert all to pdfs

**Comment by k163791** [comment]
> > > 
> > 
> > 
> > I ran into the same issue, i was using a local file, but the thing is i was trying to convert from pdf to docx, when i converted from docx to pdf everything ran smoothly, but i couldn't figure out why it was not working the other way around.
> > Does the library support conversions from pdf to other formats ?
> 
> I haven't tried the other way out...I think the purpose of the library is to interconvert right?....rather than convert all to pdfs

Yes, exactly.. that's what i thought, but when converting to pdf its working fine for me, the issue only happens when i try to convert from pdf to another format

**Comment by k163791** [comment]
I have also tried multiple filters thinking that maybe that's the issue but the error is still the same

**Comment by elwerene** [comment]
Did you try opening a pdf file in libreoffice and convert it into docx? Does this work?
It seems you are trying to do something which is not supported by libeeoffice. As this library only calls libeeoffice to convert files, you might want to open an issue in the libreoffice bugzilla.

**Comment by k163791** [comment]
> 

You're correct, I looked this up and Libreoffice actually doesn't support such thing, do you know of such a library or open source tool that does this ? convert pdf to word ? If so please do tell me. Thanks and apologies for troubling you.

**Comment by elwerene** [comment]
No, I don't know a library which is able to do this. You could maybe rasterize the pdf with imagemagick and convert it to a word document then. But I guess that's only a small part of possible use cases.

**Comment by hilmanski** [comment]
Hi @k163791 what's your take on this? currently wondering
is this library support pdf -> to other file?
or only otherformat -> pdf?

Thanks

**Comment by galaczi** [comment]
I am facing the same issue. Converting from pdf to html works. Converting to docx gives this error. Doesn't seem to be a LibreOffice issue. It swiftly converts the pdf to docx.

**Comment by mikocoral05** [comment]
this days the issue still persist when using the
const libre = require("libreoffice-convert");
but you can fix this by doing workaround
app.post("/convert-document", upload.single("file"), (req, res) => {
  const inputPath = req.file.path;
  const outputFormat = req.body.format || "pdf";
  const outputPath = path.join(
    __dirname,
    "uploads",
    `${req.file.filename}.${outputFormat}`,
  );

  console.log(`Starting conversion: ${inputPath} to ${outputPath}`);

  if (!fs.existsSync(inputPath)) {
    console.error("Input file does not exist.");
    return res.status(400).send("Input file does not exist.");
  }

  const librePath = "C:\\Program Files\\LibreOffice\\program\\soffice.exe"; // Use full path

  // Function to handle LibreOffice conversion
  const convertWithLibreOffice = (
    inputPath,
    outputPath,
    outputFormat,
    callback,
  ) => {
    const args = [
      "--headless",
      "--convert-to",
      outputFormat,
      "--outdir",
      path.dirname(outputPath),
      inputPath,
    ];

    const process = spawn(librePath, args, {
      stdio: "ignore",
      windowsHide: true,
    });

    process.on("error", (error) => {
      console.error(`Conversion error: ${error.message}`);
      callback(error);
    });

    process.on("exit", (code) => {
      if (code !== 0) {
        const error = new Error(`Conversion process exited with code ${code}`);
        console.error(error.message);
        return callback(error);
      }

      console.log(`Conversion successful: ${inputPath} to ${outputPath}`);

      // Rename the output file to include the correct extension
      const tempOutputPath = path.join(
        path.dirname(outputPath),
        req.file.filename,
      );
      fs.rename(tempOutputPath, outputPath, (err) => {
        if (err) {
          console.error(`Error renaming file: ${err.message}`);
          return callback(err);
        }
        callback(null, outputPath);
      });
    });
  };

  // Determine if we should use LibreOffice based on the output format
  const useLibreOffice = ["pdf", "docx", "odt"].includes(
    outputFormat.toLowerCase(),
  );

  if (useLibreOffice) {
    // Use LibreOffice for conversion
    convertWithLibreOffice(
      inputPath,
      outputPath,
      outputFormat,
      (err, outputFilePath) => {
        if (err) {
          return res.status(500).send(`Conversion error: ${err.message}`);
        }

        // Add a delay to ensure the file has time to be created
        setTimeout(() => {
          // Check if the output file exists
          if (!fs.existsSync(outputFilePath)) {
            console.error(`Output file does not exist: ${outputFilePath}`);
            return res.status(500).send("Output file does not exist.");
          }

          res.download(outputFilePath, (err) => {
            if (err) {
              console.error("Error sending file:", err);
            }
            // Clean up input and output files
            // deleteFile(inputPath);
            deleteFile(outputFilePath);
          });
        }, 1000); // 1-second delay
      },
    );
  } else {
    // Handle other conversions (e.g., using libreoffice-convert or other methods)
    // Example for non-LibreOffice conversions
    // Replace with actual conversion logic as needed
    const otherConversionLogic = (inputPath, outputPath, callback) => {
      // Dummy conversion logic
      fs.copyFile(inputPath, outputPath, (err) => {
        if (err) {
          return callback(err);
        }
        callback(null, outputPath);
      });
    };

    otherConversionLogic(inputPath, outputPath, (err, outputFilePath) => {
      if (err) {
        return res.status(500).send(`Conversion error: ${err.message}`);
      }

      res.download(outputFilePath, (err) => {
        if (err) {
          console.error("Error sending file:", err);
        }
        // Clean up input and output files
        deleteFile(inputPath);
        deleteFile(outputFilePath);
      });
    });
  }
});
