### ISSUE TITLE
Everybody's node app is crashing.

### ISSUE THREAD

**Issue by himanshu-grover-vm** [elwerene/libreoffice-convert#84]
Hello, 

Error while node app building with node v10:
UnhandledPromiseRejectionWarning: /home/ubuntu/app/node_modules/libreoffice-convert/index.js:17
            let paths = (options || {}).sofficeBinaryPaths ?? [];

Latest changes in the repository: 
https://github.com/elwerene/libreoffice-convert/commit/e0eae70d85c2f605b93efa0ab132503d1d2316a0#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R17

**Comment by memlucky71** [comment]
I have this problem too

**Comment by Zealotmidnight** [comment]
Node 10 doesn't support the nullish coalescing

Change node 10 to above 14.5.0+ suggest node version 15+ or lts and be careful when you migrate your node version some line of code might break.

Ref : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
Ref2 : https://node.green/#ES2021-features-Logical-Assignment-----basic-support

**Comment by Zealotmidnight** [comment]
> Hello,
> 
> Error while node app building with node v10: UnhandledPromiseRejectionWarning: /home/ubuntu/app/node_modules/libreoffice-convert/index.js:17 let paths = (options || {}).sofficeBinaryPaths ?? [];
> 
> Latest changes in the repository: [e0eae70#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R17](https://github.com/elwerene/libreoffice-convert/commit/e0eae70d85c2f605b93efa0ab132503d1d2316a0#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R17)

Node 10 doesn't support the nullish coalescing

Change node 10 to above 14.5.0+ suggest node version 15+ or lts and be careful when you migrate your node version some line of code might break.

Ref : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
Ref2 : https://node.green/#ES2021-features-Logical-Assignment-----basic-support

**Comment by elwerene** [comment]
Nice find! I'll fix it
