### ISSUE TITLE
Fit to width while converting a document to PDF

### ISSUE THREAD

**Issue by vihangmi10** [elwerene/libreoffice-convert#86]
Hello Elwerene, 
Is there a way to save any document to pdf with a setting of fit to width ? 
Kindly, help me with this.

**Comment by vihangmi10** [comment]
Hello, 
While converting .xls or .xlsx to .pdf the file is loosing its formatting. The width in the converted file is much smaller hence the excel conversion isn't depicted accurately. Is there a solution to solving this issue?

**Comment by elwerene** [comment]
Does the conversion work in libreoffice? Please check if it works there and reopen this issue if the behavior of the library differs to libreoffices behavior.

**Comment by jesse-tang-93** [comment]
same question
