### ISSUE TITLE
Convert PPT to PNG

### ISSUE THREAD

**Issue by pradella** [elwerene/libreoffice-convert#9]
I'm trying to convert PPT to PNG, but I got only the first slide converted as PNG.

Is there any option/param to convert all slides?

**Comment by elwerene** [comment]
A quick google search brought me to the conclusion, that it is not possible. But you could try this npm package: https://www.npmjs.com/package/unoconv as unoconv was an answer to your question at https://askubuntu.com/a/229507

**Comment by pradella** [comment]
Yes, actually searching on google I found the same solution, just ask to make sure.

The solution that I found and worked for me:
1) Convert the PPT to PDF using this library (libreoffice-convert)
2) Convert the PDF to images using the library pdf-image
