### ISSUE TITLE
Query on File Size

### ISSUE THREAD

**Issue by KomalAgarwal1** [elwerene/libreoffice-convert#90]
Hi Team,

I am using this library to convert word documents to pdf and it reduced the file size of pdf file to 50%.

I wanted to understand the reasons behind this. Does this package compress the file during the conversion process?

FYI.
The doc file was of size 4652 KB and the pdf file generated after conversion is having size as 2182 KB.

Please help with the above query.

**Comment by elwerene** [comment]
Please check if the conversion works in libreoffice.

If it works in libreoffice and not in this library, you can open an issue here again.
If it does not work in libreoffice, open an issue in that project.

thanks :)

**Comment by KomalAgarwal1** [comment]
Hey the conversion is working fine, but the file size is reduced so wanted to understand the reason behind it

**Comment by elwerene** [comment]
I do not do any conversion, so please check what libreoffice does ;)
my library only calls libreoffice

**Comment by KomalAgarwal1** [comment]
sure thanks for the update :)
