### ISSUE TITLE
Does anyone know to to install LibreOffice onto docker container?

### ISSUE THREAD

**Issue by bryantpa** [elwerene/libreoffice-convert#91]
Running into ERROR Error: Could not find soffice binary because I don't have the libreoffice binary on my docker container in kubernetes.  Does anyone know how I can get that binary into my k8s container?

**Comment by bryantpa** [comment]
@thgh add this to your dockerfile RUN apt-get update && apt-get -y install libreoffice.  This will install libreoffice as part of the image build process

**Comment by thgh** [comment]
Allright thanks, it works without much effort! I'm using `node:18-alpine` and this works like a charm:
```Dockerfile
RUN apk add --no-cache libreoffice
```

**Comment by hilmanski** [comment]
HI anyone know how to install the "headless" version if possible.
I assume this install 'everything'?
