### ISSUE TITLE
How to use libreoffice-convert library 

### ISSUE THREAD

**Issue by muhammadrohan3** [elwerene/libreoffice-convert#93]
How to use libreoffice-convert when deploying on platforms like heroku.

**Comment by EdwardGoomba** [comment]
This lib uses your local version (or your servers version) of open office to do the conversion.

You can't use this on a deployed platform that you don't have full control over.

**Comment by AlanGreyjoy** [comment]
Follow up question. If it's deployed on DO or Vultr, is it just as simple as apt-get libre or something similar?
