### ISSUE TITLE
How can I use this with Next.js?

### ISSUE THREAD

**Issue by salvinoto** [elwerene/libreoffice-convert#96]
So I'm trying to build a document converter with Next.js, and I'm having trouble figuring out how to use this. Should I be deploying this on for example DigitalOcean, installing LibreOffice on the server, then do some sort of API call or something to connect it with my front end? Any advice would be appreciated.

**Comment by cufta22** [comment]
@salvinoto i did it like that, deploy a separate VPS to act like an API with libreoffice installed since you can't do that with vercel edge functions, if you find a better solution i would be interested but for now this is the best i have

**Comment by salvinoto** [comment]
> @salvinoto i did it like that, deploy a separate VPS to act like an API with libreoffice installed since you can't do that with vercel edge functions, if you find a better solution i would be interested but for now this is the best i have

Thats pretty much the only idea I can think of, I'm using supabase as my backend. Have you found a way to integrate some sort of auth with it?
