### ISSUE TITLE
why i got this?

### ISSUE THREAD

**Issue by ownlight6** [elwerene/libreoffice-convert#97]
F:\LH\lightTools\node_modules\rimraf\rimraf.js:310
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\LQ\AppData\Local\Temp\libreofficeConvert_-292-DszZA0c1ISgY'
    at Object.rmdirSync (node:fs:1227:10)
    at rmkidsSync (F:\LH\lightTools工具\node_modules\rimraf\rimraf.js:349:27)
    at rmdirSync (F:\LH\lightTools工具\node_modules\rimraf\rimraf.js:329:7)
    at rimrafSync (F:\LH\lightTools工具\node_modules\rimraf\rimraf.js:301:9)
    at Object._cleanupCallback [as removeCallback] (F:\LH\lightTools工具\node_modules\tmp\lib\tmp.js:356:16)
    at F:\LH\lightTools工具\node_modules\libreoffice-convert\index.js:63:17
    at wrapper (F:\LH\lightTools工具\node_modules\async\dist\async.js:271:20)
    at F:\LH\lightTools工具\node_modules\async\dist\async.js:1143:21
    at F:\LH\lightTools工具\node_modules\async\dist\async.js:327:20
    at F:\LH\lightTools工具\node_modules\libreoffice-convert\index.js:39:32 {
  errno: -4051,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: 'C:\\Users\\LQ\\AppData\\Local\\Temp\\libreofficeConvert_-292-DszZA0c1ISgY'
}

```
async function docx2pdf() {
    try {
        const ext = '.pdf'
        const inputPath = path.join(__dirname, '/input/docx2pdf.docx');
        const outputPath = path.join(__dirname, `/output/docx2pdf${ext}`);
        const docxBuf = fs.readFileSync(inputPath);
        let pdfBuf = await libre.convertAsync(docxBuf, ext, undefined);
        console.log(pdfBuf)
        fs.writeFileSync(outputPath, pdfBuf);
    } catch (err) {
        console.log(err)
    }
}
```

**Comment by xiaoshuoyiyi** [comment]
I have the same problem

**Comment by waseem8449** [comment]
same issue

**Comment by Arthemis97** [comment]
Unsupported character in your docx file.

**Comment by nanchengjiumeng** [comment]
same error

**Comment by TasksResolver** [comment]
same error :(

**Comment by rifkidocs** [comment]
same error

**Comment by zyz9740** [comment]
At first, two similar issues have been closed here.  https://github.com/elwerene/libreoffice-convert/issues/87 https://github.com/elwerene/libreoffice-convert/issues/28

https://github.com/elwerene/libreoffice-convert/issues/87 reminders me that I should check the dependency. 


There is a misleading in the download page
![image](https://github.com/elwerene/libreoffice-convert/assets/37374623/22cefe78-6acc-45a9-84bb-bb974ef20c1c)


Please install the right package named LibreOffice_7x.x.x_Win_x86-64.msi. 
![image](https://github.com/elwerene/libreoffice-convert/assets/37374623/27476315-58fc-436e-8ff4-b388e5b97de1)


I installed the wrong package thus causing the same error. After installing the right package, it disappeared.

**Comment by ShadowSlayer03** [comment]
Same error here while trying to use the package. 
Full Error: 
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\arjun\AppData\Local\Temp\libreofficeConvert_-3868-5cYxdfMS9i7B'
    at Object.rmdirSync (node:fs:1229:10)
    at rmkidsSync (C:\Users\arjun\Documents\Web Dev Angela\Code It Yourself\PDF Merger and Converter\node_modules\rimraf\rimraf.js:349:27)
    at rmdirSync (C:\Users\arjun\Documents\Web Dev Angela\Code It Yourself\PDF Merger and Converter\node_modules\rimraf\rimraf.js:329:7)
    at rimrafSync (C:\Users\arjun\Documents\Web Dev Angela\Code It Yourself\PDF Merger and Converter\node_modules\rimraf\rimraf.js:301:9)
    at Object._cleanupCallback [as removeCallback] (C:\Users\arjun\Documents\Web Dev Angela\Code It Yourself\PDF Merger and Converter\node_modules\tmp\lib\tmp.js:356:16)
    at C:\Users\arjun\Documents\Web Dev Angela\Code It Yourself\PDF Merger and Converter\node_modules\libreoffice-convert\index.js:63:17
    at wrapper (C:\Users\arjun\Documents\Web Dev Angela\Code It Yourself\PDF Merger and Converter\node_modules\async\dist\async.js:271:20)
    at C:\Users\arjun\Documents\Web Dev Angela\Code It Yourself\PDF Merger and Converter\node_modules\async\dist\async.js:1143:21
    at C:\Users\arjun\Documents\Web Dev Angela\Code It Yourself\PDF Merger and Converter\node_modules\async\dist\async.js:327:20
    at C:\Users\arjun\Documents\Web Dev Angela\Code It Yourself\PDF Merger and Converter\node_modules\libreoffice-convert\index.js:39:32 {
  errno: -4051,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: 'C:\\Users\\arjun\\AppData\\Local\\Temp\\libreofficeConvert_-3868-5cYxdfMS9i7B'
I even went to the path and opened it to see that it was empty, maybe hidden files or smthng but there was nothing to delete manually.

**Comment by mihir254** [comment]
Came across the same issue on windows. Installed LibreOffice and checked the file path mentioned in the node module to make it work.
Code looks like:
`const libre = require('libreoffice-convert');`
`libre.convertAsync = require('util').promisify(libre.convert);`
`const pdfBuf = await libre.convertAsync(doc.getZip().generate({`
`    type: "nodebuffer",`
`    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",`
`}), 'pdf', undefined);`

And then I proceeded with using the buffer according to my use case. Thank you for sharing the resources in the above comments, it helped a lot!
Cheers!

**Comment by TasksResolver** [comment]
loadDestination: ['convert', (results, callback) =>
            async.retry({
                times: asyncOptions.times || 3,
                interval: asyncOptions.interval || 200
            }, (callback) => fs.readFile(path.join(tempDir.name, `source.${format.split(":")[0]}`), callback), callback)
        ]
       
       when using this module, source without extension .pdf is saved in temppath.
       however, 
       fs.readFile(path.join(tempDir.name, `source.${format.split(":")[0]}`), callback)
       here, fs module reads file with format .pdf .
       So I think the error was occured.
