### ISSUE TITLE
display white box for korean and asian langauge

### ISSUE THREAD

**Issue by ilovebioz** [elwerene/libreoffice-convert#99]
Hi,

I am using LibreOffice to convert my office files to pdf. I got a problem with Korean and Vietnamese. They did not display correctly after converting to pdf. Can you give a guide to solve this?

**Comment by adithyakng** [comment]
@elwerene any solution for this?

**Comment by elwerene** [comment]
Does it work in Libreoffice? If no, than please open a ticket there. If yes, you can reopen this ticket :)

**Comment by adithyakng** [comment]
It is working in Libreoffice.

**Comment by elwerene** [comment]
Is it possible for you to share the source file you want to convert to PDF?

**Comment by adithyakng** [comment]
Sure.
Here is the link:
https://docs.google.com/document/d/1sMRcVyWFXuNBlTg9jYaRbUlFzemdcLsH/edit?usp=sharing&ouid=114456190219669619839&rtpof=true&sd=true

**Comment by elwerene** [comment]
I can not reproduce this issue. I downloaded your docx file and..
 * converted it to pdf with libreoffice
 * converted it to pdf with this library which uses libreoffice
Both have, as expected, the same result.

I guess you are using another version of libreoffice where you run your nodejs code. Or you forgot to install the required fonts on that machine.
